AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String

  FileFormat:
    Type: String
    AllowedValues:
      - parquet
      - plain-text
    Default: plain-text

  Project:
    Type: String

  ResourceType:
    Type: String
    AllowedValues:
      - NetworkInterface
      - Subnet
      - VPC
      - TransitGateway
      - TransitGatewayAttachment
    Default: VPC

  ShortRegionCode:
    Type: String

  TrafficType:
    Type: String
    AllowedValues:
      - ACCEPT
      - ALL
      - REJECT
    Default: ALL

  VpcId:
    Type: String

Resources:
  FlowLogStorageBucket:
    #DeletionPolicy: Retain
    #UpdateReplacePolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${Project}-${Environment}-${ShortRegionCode}-flow-log
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 365
            NoncurrentVersionExpiration:
              NoncurrentDays: 365
            Status: Enabled
      #ObjectLockConfiguration:
      #  ObjectLockEnabled: Enabled
      #  Rule:
      #    DefaultRetention:
      #      Days: 365
      #      Mode: COMPLIANCE
      #ObjectLockEnabled: true
      #VersioningConfiguration:
      #  Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FlowLogStorageBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          #- Effect: "Deny"
          #  Principal:
          #    AWS: "*"
          #  Action:
          #    - "s3:DeleteBucket"
          #    - "s3:DeleteBucketPolicy"
          #    - "s3:PutBucketObjectLockConfiguration"
          #    - "s3:PutBucketPolicy"
          #    - "s3:PutEncryptionConfiguration"
          #    - "s3:PutLifecycleConfiguration"
          #  Resource:
          #    - !GetAtt FlowLogStorageBucket.Arn
          #- Effect: "Deny"
          #  Principal:
          #    AWS: "*"
          #  Action:
          #    - "s3:DeleteObject"
          #    - "s3:DeleteObjectVersion"
          #  Resource:
          #    - !Sub "${FlowLogStorageBucket.Arn}/AWSLogs/${AWS::AccountId}/*"
          
          # https://docs.aws.amazon.com/ja_jp/vpc/latest/userguide/flow-logs-s3-permissions.html
          - Effect: "Allow"
            Principal:
              Service: !Sub "delivery.logs.${AWS::URLSuffix}"
            Action:
              - "s3:GetBucketAcl"
            Resource:
              - !GetAtt FlowLogStorageBucket.Arn
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: "Allow"
            Principal:
              Service: !Sub "delivery.logs.${AWS::URLSuffix}"
            Action:
              - "s3:PutObject"
            Resource:
              - !Sub "${FlowLogStorageBucket.Arn}/*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
                s3:x-amz-acl: "bucket-owner-full-control"
              ArnLike:
                aws:SourceArn: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"

  FlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DestinationOptions:
        FileFormat: !Ref FileFormat
        HiveCompatiblePartitions: true
        PerHourPartition: true
      LogDestination: !GetAtt FlowLogStorageBucket.Arn
      LogDestinationType: s3
      ResourceId: !Ref VpcId
      ResourceType: !Ref ResourceType
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Environment}-${ShortRegionCode}
      TrafficType: !Ref TrafficType
